config/routes.rb
Belcanto::Application.routes.draw do

  root :to => "home#index"
  get "home/index"
  match 'schedule' => 'home#schedule', :as => :schedule

  devise_for :users

  resources :students, :only => [:index, :edit, :update] do 
    collection do
      get :autocomplete_user_first_name
    end
  end

  resources :private_lessons
  resources :cms_pages
  
  resources :files, :only => [:index] do
    member do
      get :download
    end
  end
  
  namespace :admin do
    get '/', :to => "base#index"
    resources :uploads
    resources :students do
      member do
        get :transition
      end
    end
  end
end

app/models/private_lesson.rb
class PrivateLesson < ActiveRecord::Base
  attr_accessible :user_id, :start_time, :end_time
  belongs_to :student, :class_name => 'User', :foreign_key => 'user_id'

  validates :start_time, :presence => true
  validates :end_time, :presence => true  
  validates :student, :presence => true
  
  def to_json
    {
      :id => id,
      :start => start_time,
      :end => end_time,
      :title => student.try(:full_name)
    }.to_json
  end
end

app/controllers/private_lessons_controller.rb
class PrivateLessonsController < ApplicationController
  respond_to :html, :json
  
  def index
    @private_lessons = PrivateLesson.all
    respond_with(@private_lessons) do |format|
      format.json { 
        render :text => @private_lessons.collect{ |lesson|
          { 
            "id" => lesson.id,
            "start" => lesson.start_time,
            "end" => lesson.end_time,
            "title" => lesson.student.full_name
          }
        }.to_json
      }
    end
  end
  
  def new
    @private_lesson = PrivateLesson.new
  end
  
  def create
    @private_lesson = PrivateLesson.new(params[:private_lesson])
    flash[:notice] = "Lesson successfully created" if @private_lesson.save
    respond_with(@private_lesson)
  end
  
  def edit
    @private_lesson = PrivateLesson.find(params[:id])
  end
  
  def update
    @private_lesson = PrivateLesson.find(params[:id])
    if @private_lesson.update_attributes(params[:private_lesson])
      flash[:notice] = "Successfully updated private lesson."
      redirect_to private_lessons_url
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @private_lesson = PrivateLesson.find(params[:id])
    @private_lesson.destroy
    flash[:notice] = "Successfully destroyed private lesson."
    redirect_to private_lessons_url
  end
end

app/views/private_lessons/_form.html.haml
= f.error_messages
%p
  = f.label :student
  = autocomplete_field_tag :student, '', autocomplete_user_first_name_students_path, :id_element => '#user_id'
  = f.hidden_field :user_id, :id => :user_id
%p
  = f.label :start_time
  = f.datetime_select :start_time, :minute_step => 20
%p
  = f.label :end_time
  = f.datetime_select :end_time, :minute_step => 20
%p
  = f.submit

app/views/private_lessons/edit.html.haml
- form_for @private_lesson do |f|
  = render 'form', :f => f

%p
  = link_to "Show", private_lesson_path(@private_lesson)
  |
  = link_to "View All", private_lessons_path

app/views/private_lessons/index.html.haml
%table
  %tr
    %th Student
    %th From
    %th To
  - for private_lesson in @private_lessons
    %tr{:class => cycle('even','odd')}
      %td= private_lesson.student.try(:full_name)
      %td= private_lesson.start_time.to_s(:short)
      %td= private_lesson.end_time.to_s(:short)
      %td
        = link_to 'Edit', edit_private_lesson_path(private_lesson)
        \|
        = link_to 'Delete', private_lesson, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Private Lesson", new_private_lesson_path

app/views/private_lessons/new.html.haml
- form_for @private_lesson do |f|
  = render 'form', :f => f

%p= link_to "Back to List", private_lessons_path