config/routes.rb
Belcanto::Application.routes.draw do

  root :to => "home#index"
  get "home/index"
  match 'schedule' => 'home#schedule', :as => :schedule

  devise_for :users

  resources :students, :only => [:index, :edit, :update] do 
    collection do
      get :autocomplete_user_first_name
    end
  end

  resources :private_lessons
  resources :cms_pages
  
  resources :files, :only => [:index] do
    member do
      get :download
    end
  end
  
  namespace :admin do
    get '/', :to => "base#index"
    resources :uploads
    resources :students do
      member do
        get :transition
      end
    end
  end
end

app/models/cms_page.rb
class CmsPage < ActiveRecord::Base
  acts_as_list
  attr_accessible :key, :css_class, :title, :sub_title, :nav_text, :body, :meta_keywords, :meta_description, :position, :parent_id

  validates :key, :presence => true
  validates :title, :presence => true

  default_scope order('key')

  def self.get(key)
    find_by_key(key) || self.new(:title => key, :sub_title => ':: Missing CMS Page ::')
  end

  def is_current?(uri)
    self.path.blank? ? false : uri.match(self.path)
  end

end

app/controllers/cms_pages_controller.rb
class CmsPagesController < ApplicationController
  load_and_authorize_resource
  skip_filter :get_cms_page
  before_filter :set_title
  
  def create
    if @cms_page.save
      flash[:notice] = "Successfully created cms page."
      redirect_to @cms_page
    else
      render :action => 'new'
    end
  end
    
  def update
    if @cms_page.update_attributes(params[:cms_page])
      flash[:notice] = "Successfully updated cms page."
      redirect_to @cms_page
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @cms_page.destroy
    flash[:notice] = "Successfully destroyed cms page."
    redirect_to cms_pages_url
  end

  private
  def set_title
    @title = 'CMS Pages'
  end
end

app/helpers/cms_pages_helper.rb
module CmsPagesHelper
  def head_title
    ['Art of Bel Canto',@cms_page.try(:title)].join('::')
  end
  
  def meta_description
    @cms_page.try(:meta_description) || @cms_page.try(:title)
  end

  def meta_keywords
    @cms_page.try(:meta_keywords) || @cms_page.try(:title)
  end
  
  def page_title
    @title || @student.try(:full_name) || @cms_page.try(:title)
  end

  def page_sub_title
    @student ? nil : @cms_page.try(:sub_title)
  end

end

app/views/cms_pages/_form.html.haml
= f.error_messages
%p
  = f.label :key
  = f.text_field :key

%p
  = f.label :title
  = f.text_field :title

%p
  = f.label :sub_title
  = f.text_field :sub_title

%p
  = f.label :body
  = f.text_area :body

%p
  = f.label :meta_keywords
  = f.text_area :meta_keywords

%p
  = f.label :meta_description
  = f.text_area :meta_description

%p= f.submit

app/views/cms_pages/edit.html.haml
= form_for @cms_page do |f|
  = render 'form', :f => f

%p
  = link_to "Show", @cms_page
  = link_to "View All", cms_pages_path

app/views/cms_pages/index.html.haml
%table
  %tr
    %th Title
    %th Key
    %th Body
  - for cms_page in @cms_pages
    %tr{:class => cycle('even','odd')}
      %td= cms_page.title
      %td= cms_page.key
      %td= cms_page.body
      %td= link_to "Show", cms_page
      %td= link_to "Edit", edit_cms_page_path(cms_page)
      %td= link_to "Destroy", cms_page, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Cms Page", new_cms_page_path

app/views/cms_pages/new.html.haml
- @title = 'New CMS Page'
= form_for @cms_page do |f|
  = render 'form', :f => f

%p= link_to "Back to List", cms_pages_path

app/views/cms_pages/show.html.haml
%p
  %strong Key:
  = @cms_page.key

%p
  %strong Css Class:
  = @cms_page.css_class

%p
  %strong Nav Text:
  = @cms_page.nav_text

%p
  %strong Meta Keywords:
  = @cms_page.meta_keywords

%p
  %strong Meta Description:
  = @cms_page.meta_description

%p
  = link_to "Edit", edit_cms_page_path(@cms_page) 
  \|
  = link_to "Destroy", @cms_page, :confirm => 'Are you sure?', :method => :delete 
  \|
  = link_to "View All", cms_pages_path