config/routes.rb
Belcanto::Application.routes.draw do

  root :to => "home#index"
  get "home/index"
  match 'schedule' => 'home#schedule', :as => :schedule

  devise_for :users

  resources :students, :only => [:index, :edit, :update] do 
    collection do
      get :autocomplete_user_first_name
    end
  end

  resources :private_lessons
  resources :cms_pages
  
  resources :files, :only => [:index] do
    member do
      get :download
    end
  end
  
  namespace :admin do
    get '/', :to => "base#index"
    resources :uploads
    resources :students do
      member do
        get :transition
      end
    end
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::BaseController
  before_filter :find_student, :only => [:show, :edit, :update, :destroy, :transition]
  
  def index
    @students = User.paginate :page => params[:page] || 1, :order => 'last_name asc, first_name asc'
  end
  
  def new
    @student = User.new_with_phone_numbers
  end
  
  def create
    @student = User.new(params[:user])

    if @student.save
      flash[:notice] = "The student was successfully created"
      redirect_to admin_students_path
    else
      render :action => "new"
    end
  end
  
  def update
    if @student.update_attributes(params[:user])
      flash[:notice] = "The student was successfully updated"
      redirect_to admin_student_path(@student)
    else
      render :action => "edit"
    end
  end
  
  def destroy
    if @student.destroy
      flash[:notice] = "The student was successfully removed"
      redirect_to admin_students_path
    end
  end
  
  def transition
    @student.send([params[:transition],'!'].join)
  end

  private

  def find_student
    @student = User.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_student, :validate_owner!, :only => [:edit, :update]
  
  def index
    @students = User.paginate :page => params[:page] || 1, :order => 'last_name asc, first_name asc'
  end

  def edit
    @student.phone_numbers.build if @student.phone_numbers.size == 0
    @student.files.build if @student.files.size == 0
  end
  
  def update
    if @student.update_attributes(params[:user])
      flash[:notice] = "Your student record was successfully updated"
      redirect_to students_path
    else
      render :action => "edit"
    end
  end
  
private
  
  def find_student
    @student = User.find(params[:id])
  end
  
  def validate_owner!
    authorize! :update, @student
  end
end

app/helpers/students_helper.rb
module StudentsHelper
  def phone_numbers_list(student)
    student.phone_numbers.map(&:formatted_number).join('<br >').html_safe
  end
end

app/views/students/edit.html.haml
= simple_form_for @student, :url => student_path, :html => {:method => :put, :class => :associations} do |f|
  = render 'admin/students/form', :f => f

app/views/students/index.html.haml
%table
  %tr
    %th Name
    %th Email
    %th Phone Numbers
    %th Type
    %th
  - if @students.empty?
    %tr
      %td{:colspan => "4"} There are currently no students
  - @students.each do |student|
    %tr{:class => cycle('even','odd')}
      %td{:style => "vertical-align: top"}= student.reverse_name
      %td{:style => "vertical-align: top"}= mail_to student.email
      %td{:style => "vertical-align: top"}= student.phone_numbers.map(&:formatted_number).join('<br />').html_safe
      %td{:style => "vertical-align: top"}= student.state
      %td{:style => "vertical-align: top"}= link_to 'Edit', edit_student_path(student) if can?(:update, student)
= will_paginate @students