config/routes.rb
Belcanto::Application.routes.draw do

  root :to => "home#index"
  get "home/index"
  match 'schedule' => 'home#schedule', :as => :schedule

  devise_for :users

  resources :students, :only => [:index, :edit, :update] do 
    collection do
      get :autocomplete_user_first_name
    end
  end

  resources :private_lessons
  resources :cms_pages
  
  resources :files, :only => [:index] do
    member do
      get :download
    end
  end
  
  namespace :admin do
    get '/', :to => "base#index"
    resources :uploads
    resources :students do
      member do
        get :transition
      end
    end
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::BaseController
  before_filter :find_student, :only => [:show, :edit, :update, :destroy, :transition]
  
  def index
    @students = User.paginate :page => params[:page] || 1, :order => 'last_name asc, first_name asc'
  end
  
  def new
    @student = User.new_with_phone_numbers
  end
  
  def create
    @student = User.new(params[:user])

    if @student.save
      flash[:notice] = "The student was successfully created"
      redirect_to admin_students_path
    else
      render :action => "new"
    end
  end
  
  def update
    if @student.update_attributes(params[:user])
      flash[:notice] = "The student was successfully updated"
      redirect_to admin_student_path(@student)
    else
      render :action => "edit"
    end
  end
  
  def destroy
    if @student.destroy
      flash[:notice] = "The student was successfully removed"
      redirect_to admin_students_path
    end
  end
  
  def transition
    @student.send([params[:transition],'!'].join)
  end

  private

  def find_student
    @student = User.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_student, :validate_owner!, :only => [:edit, :update]
  
  def index
    @students = User.paginate :page => params[:page] || 1, :order => 'last_name asc, first_name asc'
  end

  def edit
    @student.phone_numbers.build if @student.phone_numbers.size == 0
    @student.files.build if @student.files.size == 0
  end
  
  def update
    if @student.update_attributes(params[:user])
      flash[:notice] = "Your student record was successfully updated"
      redirect_to students_path
    else
      render :action => "edit"
    end
  end
  
private
  
  def find_student
    @student = User.find(params[:id])
  end
  
  def validate_owner!
    authorize! :update, @student
  end
end

app/helpers/students_helper.rb
module StudentsHelper
  def phone_numbers_list(student)
    student.phone_numbers.map(&:formatted_number).join('<br >').html_safe
  end
end

app/views/admin/students/_form.html.haml
= f.input :first_name
= f.input :last_name
= f.input :email

- if admin?
  = f.input :admin, :wrapper_html => {:class => :check_box}
  = f.input :editor, :wrapper_html => {:class => :check_box}

%fieldset.nested_resource
  %legend Phone Numbers
  = f.simple_fields_for :phone_numbers do |ff|
    .nested_resource_item
      = ff.input :kind, :collection => PhoneNumber::KINDS, :include_blank => false
      = ff.input :number
      %p.remove_field
        = ff.check_box :_destroy
        = ff.label :_destroy, 'Delete'

  %p.add_field
    %a{:href => '#'} Add another phone number

%fieldset
  %legend Tape Access
  - Upload.all.each do |file|
    %p.check_box
      - file_id = ['file',file.id].join('-')
      = check_box_tag 'user[file_ids][]', file.id, @student.files.include?(file), :id => file_id
      %label{:for => file_id}= file.title

= f.submit

app/views/admin/students/_navigation.html.haml
%p
  = link_to '[Student List]', admin_students_path
  = link_to '[Add New Student]', new_admin_student_path
  - if @student and not @student.new_record?
    = link_to '[Edit This Student]', edit_admin_student_path(@student)
    = link_to '[Delete This Student]', admin_student_path(@student), :method => :delete, :confirm => "Are you sure?"

app/views/admin/students/edit.html.haml
= simple_form_for [:admin, @student], :url => admin_student_path, :html => {:method => :put, :class => :associations} do |f|
  = render 'admin/students/form', :f => f
= render 'navigation'

app/views/admin/students/index.html.haml
%table
  %tr
    %th Name
    %th Email
    %th Phone Numbers
    %th Admin
    %th Editor
    %th Type
    %th
    %th
  - if @students.empty?
    %tr
      %td{:colspan => "4"} There are currently no students
  - @students.each do |student|
    %tr{:class => cycle('even','odd')}
      %td= link_to student.reverse_name, admin_student_path(student)
      %td= mail_to student.email
      %td= phone_numbers_list student
      %td= is? student.admin
      %td= is? student.editor
      %td
        = form_tag do
          = hidden_field_tag 'student_id', student.id
          = select_tag '#', options_for_select(User.states, student.state), 
            :class => 'state_select_dropdown', 
            :id => "state_select_dropdown_#{student.id}"
      %td= link_to 'Edit', edit_admin_student_path(student)
      %td= link_to 'Remove', admin_student_path(student), :method => :delete, :confirm => "Are you sure?"

= will_paginate @students

= render 'navigation'

app/views/admin/students/new.html.haml
= simple_form_for [:admin, @student], :url => admin_students_path, :html => {:class => :associations} do |f|
  = render 'admin/students/form', :f => f
  
= render 'navigation'

app/views/admin/students/show.html.haml
%p
  = mail_to @student.email
%p
  = phone_numbers_list @student
  
- if admin?
  %p
    Admin: 
    = is? @student.admin
  %p
    Editor:
    = is? @student.editor
  %p
    Type:
    = form_tag do
      = hidden_field_tag 'student_id', @student.id
      = select_tag '#', options_for_select(User.states, @student.state), :class => 'state_select_dropdown', :id => "state_select_dropdown_#{@student.id}"
    
= render 'navigation'

app/views/admin/students/transition.js.erb
$('#flash').html('<%= escape_javascript(render 'shared/flashes') %>')